export default {
  name: 'siteSettings',
  title: 'Website',
  type: 'document',
  groups: [
    { name: 'brand', title: 'Marke', default: true },
    { name: 'contact', title: 'Kontakt' },
    { name: 'vehicles', title: 'Fahrzeuge' },
  ],
  fields: [
    {
      name: 'brandName',
      title: 'Name',
      type: 'string',
      group: 'brand',
      validation: (R) => R.required(),
    },
    {
      name: 'contactName',
      title: 'Ansprechpartner',
      type: 'string',
      group: 'brand',
      validation: (R) => R.required(),
    },
    {
      name: 'logo',
      title: 'Logo',
      type: 'image',
      group: 'brand',
      options: { hotspot: true },
      fields: [{ name: 'alt', title: 'Alt-Text', type: 'string' }],
      validation: (R) => R.required(),
    },
    { name: 'phone', title: 'Telefon', type: 'string', group: 'contact' },
    {
      name: 'instagramUrl',
      title: 'Instagram-Profil',
      type: 'url',
      group: 'contact',
      validation: (R) => R.uri({ scheme: ['https'] }),
    },
    {
      name: 'whatsapp',
      title: 'WhatsApp-Nummer',
      type: 'string',
      group: 'contact',
      description: 'International, ohne + und Leerzeichen, z. B. 491751234567',
    },
    {
      name: 'email',
      title: 'E-Mail',
      type: 'string',
      group: 'contact',
      validation: (R) => R.email(),
    },
    {
      name: 'featuredVehicleCount',
      title: 'Anzahl Fahrzeuge auf der Startseite',
      type: 'number',
      group: 'vehicles',
      description:
        'Anzahl im horizontalen Startseiten-Slider. 0 = alle sichtbaren Fahrzeuge; die Reihenfolge wird am Fahrzeug festgelegt.',
      initialValue: 3,
      validation: (R) => R.required().min(0).integer(),
    },
    {
      name: 'priceNote',
      title: 'Allgemeiner Preis-Hinweis',
      type: 'text',
      rows: 2,
      group: 'vehicles',
      validation: (R) => R.required(),
    },
  ],
  preview: { prepare: () => ({ title: 'Website' }) },
};
